name: generate-docs
on: 
  push:
    branches:
      - main

jobs:
  # This job generates documentation
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install data & dependencies
      run: |
        pip install pytest
        pip install -r requirements.txt
        pip install -e .

    - name: Install sphinx
      run: |
        sudo apt-get install python3-sphinx
        sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    - name: Run sphinx
      run: |
        cd docs
        sphinx-build -b latex source build
        make latexpdf

    - name: move docs
      run: |
        sudo mv docs/build/latex/DD-GAN-AE.pdf docs/docs.pdf

    - name: commit files
      run: |
        git add docs
        git config --global user.email "zrw20@ic.ac.uk"
        git config --global user.name "acse-zrw20"
        git commit -m "automatically added docs"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}